web:
  build: .
  ports:
    - "3030:3000"
  links:
    - "cache:redis"
    - db

cache:
  image: redis

db:
  image: mysql
  environment:
    MYSQL_USER: "forge_user"
    MYSQL_PASSWORD: "forge_password"
    MYSQL_ROOT_PASSWORD: "my_secret_password"