web:
  build: .
  ports:
    - "3030:3000"
  links:
    - "cache:redis"
    - db
  volumes:
    - ./src:/src
  environment:
    GITHUB_CLIENT_SECRET: "${GITHUB_CLIENT_SECRET}"

cache:
  image: redis

db:
  image: mysql
  environment:
    MYSQL_USER: "forge_user"
    MYSQL_PASSWORD: "forge_password"
    MYSQL_ROOT_PASSWORD: "my_secret_password"
    MYSQL_DATABASE: "forge-db"
  volumes:
   - ./db:/docker-entrypoint-initdb.d